# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Nimbl3' do
pod "AFNetworking", "~> 3.0"
#pod 'CocoaLumberjack'
pod 'SVProgressHUD', :head

end

target 'Nimbl3Tests' do

end

target 'Nimbl3UITests' do

end

